"""empty message

Revision ID: 74b471a6429b
Revises: 016765b6f4a2
Create Date: 2023-05-25 23:09:49.428846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74b471a6429b'
down_revision = '016765b6f4a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmarks', sa.Column('owner_id', sa.String(length=36), nullable=False))
    op.drop_constraint('bookmarks_user_id_fkey', 'bookmarks', type_='foreignkey')
    op.create_foreign_key(None, 'bookmarks', 'users', ['owner_id'], ['id'])
    op.drop_column('bookmarks', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmarks', sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'bookmarks', type_='foreignkey')
    op.create_foreign_key('bookmarks_user_id_fkey', 'bookmarks', 'users', ['user_id'], ['id'])
    op.drop_column('bookmarks', 'owner_id')
    # ### end Alembic commands ###
