"""empty message

Revision ID: 352039f368f0
Revises: 7b3c4a6bd832
Create Date: 2023-05-22 14:05:08.983390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '352039f368f0'
down_revision = '7b3c4a6bd832'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('headers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('headers',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('text', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('profile_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name='headers_profile_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='headers_pkey')
    )
    # ### end Alembic commands ###
