"""empty message

Revision ID: a751b1911c08
Revises: ea747b6bb3c9
Create Date: 2023-05-18 19:54:35.908942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a751b1911c08'
down_revision = 'ea747b6bb3c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.Column('lastname', sa.String(length=16), nullable=True),
    sa.Column('profile_picture', sa.String(length=255), nullable=True),
    sa.Column('banner', sa.String(length=255), nullable=True),
    sa.Column('place_of_work', sa.String(length=40), nullable=True),
    sa.Column('education', sa.String(length=40), nullable=True),
    sa.Column('phone_number', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=40), nullable=True),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('galleries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('headers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('link_type', sa.String(length=25), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gallery_images',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.Column('gallery_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['gallery_id'], ['galleries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gallery_images')
    op.drop_table('links')
    op.drop_table('headers')
    op.drop_table('galleries')
    op.drop_table('profiles')
    # ### end Alembic commands ###
