"""empty message

Revision ID: 016765b6f4a2
Revises: a1475f13e97d
Create Date: 2023-05-25 23:07:25.656981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '016765b6f4a2'
down_revision = 'a1475f13e97d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookmarks', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookmarks', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    # ### end Alembic commands ###
