"""empty message

Revision ID: f1172fa8ff94
Revises: eb6092a1cf7a
Create Date: 2023-05-23 12:46:21.708485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1172fa8ff94'
down_revision = 'eb6092a1cf7a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmarks', sa.Column('user_id', sa.String(length=36), nullable=False))
    op.drop_constraint('bookmarks_owner_id_fkey', 'bookmarks', type_='foreignkey')
    op.create_foreign_key(None, 'bookmarks', 'users', ['user_id'], ['id'])
    op.drop_column('bookmarks', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmarks', sa.Column('owner_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'bookmarks', type_='foreignkey')
    op.create_foreign_key('bookmarks_owner_id_fkey', 'bookmarks', 'users', ['owner_id'], ['id'])
    op.drop_column('bookmarks', 'user_id')
    # ### end Alembic commands ###
