"""empty message

Revision ID: a1475f13e97d
Revises: 6082cab8c7aa
Create Date: 2023-05-25 16:18:14.138740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1475f13e97d'
down_revision = '6082cab8c7aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookmarks', 'profile_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column('bookmarks', 'profile_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    # ### end Alembic commands ###
