"""empty message

Revision ID: 3215d8a9c5d5
Revises: 89bc2c220425
Create Date: 2023-05-22 21:18:28.557228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3215d8a9c5d5'
down_revision = '89bc2c220425'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('order', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'order')
    # ### end Alembic commands ###
