"""empty message

Revision ID: c3f6105a747b
Revises: 3ce35b0619f5
Create Date: 2023-05-21 18:50:49.096961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3f6105a747b'
down_revision = '3ce35b0619f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('headers', 'profile_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('links', 'profile_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('links', 'profile_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('headers', 'profile_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    # ### end Alembic commands ###
