"""empty message

Revision ID: ea747b6bb3c9
Revises: 11adbb7ba420
Create Date: 2023-05-13 22:44:49.853888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea747b6bb3c9'
down_revision = '11adbb7ba420'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
