"""empty message

Revision ID: 846ddba8070f
Revises: c3f6105a747b
Create Date: 2023-05-22 13:11:48.254827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '846ddba8070f'
down_revision = 'c3f6105a747b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'created_at')
    # ### end Alembic commands ###
