"""empty message

Revision ID: 162e2bdaa27d
Revises: 66da8ef5de07
Create Date: 2023-05-20 17:17:25.530514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '162e2bdaa27d'
down_revision = '66da8ef5de07'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_education_info')
    op.drop_table('contact_info')
    op.add_column('profiles', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('profiles', sa.Column('email', sa.String(length=40), nullable=True))
    op.add_column('profiles', sa.Column('job', sa.String(length=40), nullable=True))
    op.add_column('profiles', sa.Column('education', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'education')
    op.drop_column('profiles', 'job')
    op.drop_column('profiles', 'email')
    op.drop_column('profiles', 'phone_number')
    op.create_table('contact_info',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('profile_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name='contact_info_profile_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='contact_info_pkey')
    )
    op.create_table('job_education_info',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('job', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('education', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('profile_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name='job_education_info_profile_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='job_education_info_pkey')
    )
    # ### end Alembic commands ###
