"""empty message

Revision ID: 8901db871631
Revises: a751b1911c08
Create Date: 2023-05-20 14:11:18.521239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8901db871631'
down_revision = 'a751b1911c08'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_info',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=40), nullable=True),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_education_info',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job', sa.String(length=40), nullable=True),
    sa.Column('education', sa.String(length=40), nullable=True),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('profiles', 'education')
    op.drop_column('profiles', 'email')
    op.drop_column('profiles', 'place_of_work')
    op.drop_column('profiles', 'phone_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('phone_number', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('place_of_work', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('email', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('education', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.drop_table('job_education_info')
    op.drop_table('contact_info')
    # ### end Alembic commands ###
